<?php 

  class Myapp extends JsonView {
    /**
     * This is an autogenerated code for started project
     **/
    public function index(){
      return '{"message": "Congratulation this is your first service using primal"}';
    }
  }